spring.application.name=inventory
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/db_inventario
spring.datasource.username=alumno
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
